name: job_portal
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  lottie: ^3.3.1
  intl: ^0.20.2
  provider: ^6.0.5
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  http: ^1.2.2
  firebase_storage: ^13.0.2
  firebase_auth: ^6.1.0
  google_fonts: any
  html: ^0.15.6
  file_picker: ^10.3.3
  flutter_svg: ^2.0.17
  another_flushbar: ^1.12.30
  go_router: ^16.2.4
  pdf: ^3.10.4
  timeago: ^3.3.0
  cached_network_image: ^3.4.1
  printing: ^5.10.0
  google_sign_in: ^6.3.0
  fl_chart: ^1.0.0
  flutter_date_pickers: ^0.4.3
  rxdart: ^0.28.0
  url_launcher: ^6.3.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/logo.jpeg
    - images/logo_main.png
    - images/splash.webp
    - images/signup_recruiter.svg
    - images/signup_jobseeker.svg
    - images/login_recruiter.svg
    - images/login_jobseeker.svg
    - images/forgot.svg
    - images/recruiter_2.svg
    - images/success.json
    - images/MaterialIcons-Regular.ttf
